@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Execute Imports

actor Admin as act

participant "<u>:ImportExecutionForm" as view
participant "<u>:ExecuteImportController" as ctrl
participant "<u>:ImportItem" as pro
participant "<u>:ImportItemDAO" as dao
participant "<u>:DBContext" as ctx

database Database as db

act++
act->view++:1.Click the "Import" button
view->view++:2.Validate input
group opt [Invalid input]
    view-->act:2.1.Display error message
end
view--
view->ctrl++:3.doPost()
loop for each selected pending import
    ctrl->pro++:4.new ImportItem()
    pro-->ctrl--:5.Return ImportItem object, add to List<ImportItem>
end
ctrl->dao++:6.executeImports()
dao->ctx++:7.exeNonQuery()
ctx -> db++:8.UPDATE import status of selected pending imports
db -->ctx:9.Return numberOfRowsAffected
ctx -->dao:10.Return numberOfRowsAffected
alt numberOfRowsAffected > 0
    dao->ctx:10.1.exeNonQuery()
    ctx->db:10.1.1.UPDATE stockCount of the imported products,\nincreased by the total quantity of imports
    db-->ctx--:10.1.2.Return numberOfRowsAffected
    ctx -->dao--:10.1.3.Return numberOfRowsAffected
    alt numberOfRowsAffected > 0
        dao-->ctrl:10.1.3.1.Return true
        ctrl-->view:10.1.3.1.1.Return successful message
        view-->act:10.1.3.1.2.Display the message
    else numberOfRowsAffected == 0
        dao-->ctrl:10.1.3.2.Return error message
        ctrl-->view:10.1.3.2.1.Return error message
        view-->act:10.1.3.2.2.Display the message
    end
else numberOfRowsAffected == 0
    dao-->ctrl--:10.2.Return error message
    ctrl-->view--:10.2.1.Return error message
    view-->act--:10.2.2.Display the message
end
act--
@enduml