@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Queue New Imports

actor Admin as act

participant "<u>:ImportQueueingForm" as view
participant "<u>:QueueImportController" as ctrl
participant "<u>:ImportItem" as pro
participant "<u>:ImportItemDAO" as dao
participant "<u>:DBContext" as ctx

database Database as db

act++
act->view++:1.Click the "Save" button
view->view++:2.Validate input
group opt [Invalid input]
    view-->act:2.1.Display error message
end
view--
view->ctrl++:3.doPost()
loop for each selected product supply
ctrl->pro++:4.new ImportItem()
pro --> ctrl--:5.Return ImportItem object,\nadd to List<ImportItem>
end
ctrl->dao++:6.queueImports()
dao->ctx++:7.exeNonQuery()
ctx -> db++:8.INSERT a new row to ImportItem table
db -->ctx--:9.Return numberOfRowsAffected
ctx -->dao--:10.Return numberOfRowsAffected
alt numberOfRowsAffected == 0
    dao-->ctrl:10.1.Return false
    ctrl-->view:10.1.1.Return failed message
    view-->act:10.1.2.Display the message
else numberOfRowsAffected > 0
    dao-->ctrl--:10.2.Return true
    ctrl-->view--:10.2.1.Return successful message
    view-->act--:10.2.2.Display the message
end

@enduml