@startuml
<style>
 sequenceDiagram {
        actor { BackgroundColor white; LineThickness 1.0 }
        participant { BackgroundColor white; RoundCorner 0 }
        database { BackgroundColor white }
    }
    
</style>

hide footbox

mainframe View Product List (Apply to Customer as well)

actor Guest as act

participant "<u>:ProductListView" as view
participant "<u>:ViewProductListController" as ctrl
participant "<u>:Utility" as util
participant "<u>:ProductDAO" as dao
participant "<u>:Product" as product
participant "<u>:DBContext" as ctx

database Database as db


activate act
act->view++:1.Select a classification option
note left of view: [classification option] can be :\n- Category\n- Creator\n- Publisher, Genre\n- Series, Brand, Character\n- NewRelease, OnSale
view->ctrl++:2.doGet()
ctrl->ctrl++:3.getClassificationAttributes()
ctrl--
ctrl->util++:4.getDefaultSortCriteria()
util-->ctrl--:5.Return sortCriteria
ctrl->dao++:6.getClassifiedProductList()
dao->ctx++:7.exeQuery()
ctx -> db++:8.SELECT rows from Product table\nbased on classification, pageNumber
db -->ctx:9.Return ResultSet
ctx-->dao:10.Return ResultSet
dao->dao++:11.Instantiate List<Product>
dao--
alt ResultSet is not empty
    loop ResultSet.next() == true
        dao -> product++:11.1.new Product()
        product --> dao--:11.1.1.Return product object
        dao->dao++:11.1.2.Add product object to List<Product>
        dao--
    end

    dao --> ctrl:11.1.3.Return List<Product>
    ctrl ->dao:11.1.4.countClassifiedProductList()
    dao -> ctx:11.1.5.exeQuery()
    ctx -> db:11.1.6.SELECT COUNT(*) from Product table\nbased on classification
    db-->ctx--:11.1.7.Return ResultSet
    ctx-->dao--:11.1.8.Return ResultSet
    dao --> ctrl:11.1.9.Return productCounts
    ctrl --> view:11.1.10.Return List<Product> and productCounts
    loop For each product in List<Product>
        view --> act:11.1.11.Display product general information
    end
else ResultSet is empty
    dao --> ctrl--: 11.2.Return an empty list
    ctrl --> view--: 11.2.1.Return failed message
    ctrl--
    ctrl--
    view --> act--:11.2.2.Display the message
end
deactivate act
@enduml