name: ProjectSWP391 CI

on:
  push:
    branches: [ an ]
  pull_request:
    branches: [ an ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 13 (Zulu)
      uses: actions/setup-java@v3
      with:
        java-version: '13.0.2'
        distribution: 'zulu'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -B

    - name: Run Tests
      run: mvn test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/*.xml

    - name: Upload WAR artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mavenproject7
        path: target/*.war

  deploy:
    needs: build
    runs-on: windows-latest  # Runs on your Windows machine

    steps:
    - name: Download WAR artifact
      uses: actions/download-artifact@v4
      with:
        name: mavenproject7
        path: target/

    - name: Stop Tomcat
      run: |
        C:\apache-tomcat-10.1.29\bin\shutdown.bat

    - name: Copy WAR to Tomcat webapps
      run: |
        copy target\*.war C:\apache-tomcat-10.1.29\webapps\

    - name: Start Tomcat
      run: |
        C:\apache-tomcat-10.1.29\bin\startup.bat
