name: ProjectSWP391 CI

# Workflow Triggers
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# Job Setup (named 'build')
jobs:
  build:
    runs-on: ubuntu-20.04  # Setup environment (VM) - Older version with broader JDK support
    
    steps:
    # Fetch Respository Code
    - name: Checkout code   
      uses: actions/checkout@v3
    
     #Sets up Java 13 using the Zulu OpenJDK distribution.
    - name: Set up JDK 13 (Zulu)   
      uses: actions/setup-java@v3
      with:
        java-version: '13.0.2'
        distribution: 'zulu'
    
    # Cache Dependencies (Dependencies will only be downloaded again if pom.xml changes.)
    - name: Cache Maven packages    
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Clean and Build the Project (-B to disable interactive prompts in CI environments. )
    - name: Build with Maven    
      run: mvn clean package -B

    # Run automation tests (JUnit, Selenium, etc.)
    - name: Run Tests
      run: mvn test

    # Upload Test Reports (optional - allow others to download and review)
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/*.xml

    # Run PMD Static Analysis
    - name: Run PMD
      run: mvn pmd:check || true  # Allow workflow to continue even if PMD finds issues (avoid BUILD FAILED for non-critical issues)

    # Upload PMD Reports (same as Test Reports)
    - name: Upload PMD Report
      uses: actions/upload-artifact@v4
      with:
        name: pmd-report
        path: target/site/pmd.html

    # Upload WAR file after tests pass (for further testing or deployment)
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: mavenproject7
        path: target/*.war
