name: ProjectSWP391 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04  # Older image with broader JDK support

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 13 (Zulu)
      uses: actions/setup-java@v3
      with:
        java-version: '13.0.2'
        distribution: 'zulu'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -B

    # Run automation tests (JUnit, Selenium, etc.)
    - name: Run Tests
      run: mvn test

    # Upload Test Reports (optional)
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/*.xml

    # Run PMD Static Analysis
    - name: Run PMD
      run: mvn pmd:check || true  # Allow workflow to continue even if PMD finds issues

    # Upload PMD Reports
    - name: Upload PMD Report
      uses: actions/upload-artifact@v4
      with:
        name: pmd-report
        path: target/site/pmd.html

    # Upload WAR file after tests pass
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: mavenproject7
        path: target/*.war
