name: ProjectSWP391 CI

on:
  push:
    branches: [ an ]
  pull_request:
    branches: [ an ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 13
      uses: actions/setup-java@v3
      with:
        java-version: '13.0.2'  # Exact version from Adoptium archives
        distribution: 'temurin'
        java-package: 'jdk'     # Ensures full JDK, not JRE
        architecture: 'x64'     # Matches most runners

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -B

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: mavenproject7
        path: target/*.war
